#!/usr/bin/env python3

import argparse
from datetime import date

from pyinvest import auth, accounts, config

parser = argparse.ArgumentParser()
parser.add_argument('--config', '-c', type=str, default='$HOME/config/pyinvest.json')
parser.add_argument('--verbose', '-v', action='store_true')
args = parser.parse_args()

info = config.Config(args.config)

access_token = auth.authenticate(info.refresh_token, info.client_id)

td_ameritrade = accounts.TDAmeritradeClient(access_token, info.account_id)
account_info = td_ameritrade.get_account_info()
positions = td_ameritrade.get_positions()

total_account_value = account_info['currentBalances']['liquidationValue']
available_cash = account_info['currentBalances']['cashAvailableForTrading']
position_value = account_info['currentBalances']['longMarketValue']
today = date.today().strftime('%m/%d/%Y')

print("\n")
print(f"Info for account #{info.account_id} - {today}")
print("-------------------------------------------------------")
print(f"Cash available for trading: ${available_cash}")
print(f"Positions: ${position_value}")
print(f"Total account value: ${total_account_value}")
print("\n")

total_profit = 0

if args.verbose:
    print("Positions")
    print("------------------------------------------------------------------------------")

for asset in positions:
    symbol = asset['instrument']['symbol']
    current_price = asset['marketValue'] / asset['longQuantity']
    asset_profit = accounts.calculate_total_profit(asset['longQuantity'],
                                                   asset['averagePrice'],
                                                   current_price)
    total_profit += asset_profit

    asset_profit_pcnt = accounts.calculate_total_profit_percentage(asset['longQuantity'],
                                                                   asset['averagePrice'],
                                                                   current_price)
    
    if symbol == 'MMDA1':
        continue  # Skip Money Market value

    quantity = asset['longQuantity']
    avg_price = asset['averagePrice']
    market_value = asset['marketValue']
    current_profit = asset['currentDayProfitLoss']
    current_profit_pcnt = asset['currentDayProfitLossPercentage']

    if args.verbose:
        print(f"Symbol: {symbol}, Long quantity: {quantity}, Market value: {market_value}")
        print(f"Current price: {current_price}, Average price: {avg_price}")
        print(f"Day gain/loss: {current_profit}, {current_profit_pcnt}%")
        print(f"Total gain/loss: {asset_profit}, {asset_profit_pcnt}%")
        print("------------------------------------------------------------------------------")

dec = (total_account_value / (total_account_value - total_profit)) - 1
total_profit_pcnt = round(dec * 100, 2)
print(f"Total profit: {total_profit}, {total_profit_pcnt}%\n")

